### ISSUE TITLE
Translate quickstart

### ISSUE THREAD

**Issue by krancour** [brigadecore/docs-portuguese#1]
It was suggested in yesterday's community meeting that we don't need to wait for the entire doc tree to be translated in order to start publishing the Portuguese translation. We can prioritize and go after the highest value content first.

I'm opening this issue just to suggest that the [QuickStart](https://github.com/brigadecore/brigade/blob/main/docs/content/intro/quickstart.md) is  our highest value piece of content. We could start publishing the Portuguese translation as soon as even just that one page is translated. 😄

**Comment by jorgearteiro** [comment]
I am taking this one, then we can start publishing the Portuguese Translation.
